name: ci

# This event triggered when PR being made

on:
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

        # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '1.17.4' # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format -n --set-exit-if-changed -- --line-length 140 .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '1.17.4' # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

      # Run widget tests for our flutter project.
      - run: flutter test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
          with:
            java-version: '12.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '1.17.4'


      # Get flutter dependencies.
      - run: flutter pub get
      # build android
      - run: flutter build apk --debug --split-per-abi